version: '3'
services:
  webapp:
    build: .
    ports:
      - "3000:3000"
  socket-server:
    build: .
    ports:
      - "5000:5000"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
